# Generated by Django 6.0 on 2025-12-20 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('service_type', models.CharField(choices=[('product', 'Producto & Web3'), ('teaching', 'Docencia / Consultoría')], max_length=50, verbose_name='Tipo de consulta')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Consulta de contacto',
                'verbose_name_plural': 'Consultas de contacto',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
